# Generated by Django 5.0.4 on 2024-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_profession_radiofeilds_textfeild2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFeilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('userdetail', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('require', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('phnum', models.CharField(max_length=100)),
                ('expectation', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='FileFeilds',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='RadioFeilds',
        ),
        migrations.DeleteModel(
            name='TextFeild1',
        ),
        migrations.DeleteModel(
            name='TextFeild2',
        ),
    ]
