# Generated by Django 5.0.4 on 2024-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_formfeilds_rename_files_filefeilds_delete_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfeilds',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
