# Generated by Django 5.0.4 on 2024-06-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_contactfeilds'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactfeilds',
            name='Cdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contactfeilds',
            name='Cday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactfeilds',
            name='Cprofession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
